#!/bin/bash

while true; do
    read -p "Enter a positive number: " num
    if [[ $num -gt 0 ]]; then
        echo "You entered: $num"
        break
    else
        echo "Please enter a positive number."
    fi
done

